# Numpy Módulo 2
## Operações com Arrays Numpy
### Com Escalares

In [10]:
import numpy as np

np.random.seed(32) #manter o número aleatório

a1 = np.random.randint(1, 20, 8)

In [14]:
print(a1)

# operações aritméticas com arrays
a1 - 2
a1 ** 2


[12  6  8  4  6 11 10  5]


array([144,  36,  64,  16,  36, 121, 100,  25])

### Entre Arrays

In [20]:
a2 = np.random.randint(1, 100, 8)

In [21]:
a2

array([83, 11, 85, 51, 58, 70, 39, 78])

In [26]:
print(a1 + a2)
print(a1 - a2)
print(a1 * a2)

[95 17 93 55 64 81 49 83]
[-71  -5 -77 -47 -52 -59 -29 -73]
[996  66 680 204 348 770 390 390]


In [27]:
# (3 x 2) x (2 x 3) = (3 x 3)
m1 = np.random.randint(1, 10, (3, 2))
m2 = np.random.randint(1, 10, (2, 3))

print(m1)
print(m2)

[[9 5]
 [1 7]
 [5 1]]
[[4 3 6]
 [4 3 9]]


In [28]:
# multiplicação de matriz, linhas por colunas
m1.dot(m2)

array([[56, 42, 99],
       [32, 24, 69],
       [24, 18, 39]])

### Comparações

In [30]:
a1 = np.array([1, 2, 2, 1])
a2 = np.array([3, 2, 3, 1])

a1 == a2 # verifica cada posição e retorna um valor booleano se for igual ou não

np.array_equal(a1, a2) # aqui existe uma comparação de matrizes, para ser verdadeiro ambas as matrizes precisam ter valores iguais em todos os elementos

False

In [33]:
# funções matemáticas 
# todos os comandos funcionam da mesma forma - np.<função matemática>(<array>)
# Link da documentação: https://numpy.org/doc/1.18/reference/routines.math.html

np.sum(m2)
np.mean(a1)
np.var(a1)

0.25