<h1>Numpy</h1>

In [1]:
import numpy as np

In [2]:
arr = np.array([0, 1, 2, 3]) #Criação de um Array
print(arr)
print(type(arr))

[0 1 2 3]
<class 'numpy.ndarray'>


<h1>Criação de Arrays</h1>
<p>Contrução Manual de Arrays</p>

In [3]:
b = np.array([[0, 1, 2],[3, 4, 5]])
print(b)
print(b.ndim) #dimensão do array
print(b.shape) #mostra o formato do array

[[0 1 2]
 [3 4 5]]
2
(2, 3)


<p>Criação utilizando funções</p>

In [5]:
c = np.arange(0, 100, 1) #inicio, fim, e de quanto em quanto
display(c)

d = np.linspace(1, 10, 10, endpoint=False) #inclui o número posto no código, último parametro é a quantidade de números entre o primeiro e último número.
#endpoint n ira incluir o último número, então ela irá até o 9.
display(d)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

<p>Arrays Comuns</p>

In [9]:
e = np.ones((5,5)) #apenas com número 1
print(e)

f = np.random.rand(5,5)
print(f)

d = np.eye(3) # tera valor 1 em sua diagonal
print(d)

e = np.diag(np.array([1,2,3])) # uma matriz que n é possível montar sua dimensão, todos os valores que vc colocar nela, será na diagonal, então a dimensão dela vai depender da quantidade de número colocado dentro dela.
print(e)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0.76783879 0.88749187 0.87369589 0.60769938 0.6220541 ]
 [0.98300675 0.62318279 0.51722073 0.5673179  0.86120063]
 [0.24542583 0.79579487 0.35978635 0.10493327 0.62825862]
 [0.10611562 0.94377756 0.39607723 0.9133458  0.53581874]
 [0.18804239 0.81971218 0.45084082 0.02501868 0.90542445]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


<h3>Exercícios

In [18]:
# Crie uma matriz identidade com dimensão 5x5
ex1 = np.eye(5,5)
print(ex1)

#crie uma matriz 3x3 com todos os elementos iguais a 1.
ex2 = np.ones((3,3))
print(ex2)

#crie uma matriz 2x3 com elementos de valores aleatórios entre 0 e 20
ex3 = np.random.randint(20, size=(2, 3))
print(ex3)

#crie o vetor: [9, 8, 7, 6, 5, 4, 3, 2, 1]
ex4 = np.arange(9, 0, -1)
print(ex4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 2 16  2]
 [15  0 15]]
[9 8 7 6 5 4 3 2 1]


<h2>Indexação e Corte (Slices) de Arrays

In [35]:
a = np.arange(10)
print(a)

a[0]
a[-1]

#Slices
print(a[0:5]) # o resultado é parecido com o Limit do SQL
print('\n')

print(a[2:9:2]) # nesse caso o terceiro valor indica de quanto em quanto será mostrado na tela, ou seja, está pulando de 2 em 2 dentro do intervalo de 2 a 9-1.

print('\n')
print(a[8:2:-1]) # aqui o array está invertido, e para percorrer ele devemos colocar -1, pois, indica o final do array

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


[2 4 6 8]


[8 7 6 5 4 3]


In [33]:
b = np.random.rand(5, 5)
b
print(b[0]) #linha inteira
b[0, 1] #valor específico
print('\n')

#slice
print(b[0:2]) # nesse caso sendo um array multidimensional, os valores colocados são referentes as linhas ou seja, nesse caso vou imprimir a linha 0 e a (2 -1), será mostrado apenas as linhas 0 e 1.

print('\n')
print(b)
print('\n')
print(b[0:2, 2]) # aqui esse último valor indica o indíce de colunas, então o valor mostrado foi da terceira coluna, pois o inicio é 0.

[0.00208057 0.78687187 0.74813055 0.42941381 0.45245389]


[[0.00208057 0.78687187 0.74813055 0.42941381 0.45245389]
 [0.82527768 0.33204085 0.60856223 0.80562037 0.60335075]]


[[0.00208057 0.78687187 0.74813055 0.42941381 0.45245389]
 [0.82527768 0.33204085 0.60856223 0.80562037 0.60335075]
 [0.54143578 0.14041203 0.7750218  0.91157206 0.5810503 ]
 [0.7716598  0.43323397 0.63506324 0.50830836 0.64917974]
 [0.23689406 0.08686521 0.05263145 0.13764878 0.42471822]]


[0.74813055 0.60856223]
