# Aula 3
## Métodos Importantes e Máscaras em Arrays

#### 1. Métodos Importantes
* ndim
* shape
* dtype
* astype
* min
* max
* argmin
* argmax
* sum
* mean
* var
* std
* sort
* T
* reshape

In [1]:
import numpy as np

In [2]:
array = np.random.randn(10)

In [3]:
array

array([ 1.74458883, -0.13843418, -1.32423947, -0.22727839, -2.0291442 ,
        0.04383233, -0.0408311 ,  0.22448472, -1.43615399, -0.2243564 ])

In [6]:
mtx = np.random.randn(3, 3)

In [7]:
mtx

array([[ 0.9439145 ,  0.48749991,  0.99424054],
       [ 0.16826415, -0.06389469, -0.28131346],
       [-0.11922921, -0.39774131, -0.03310841]])

In [9]:
array.ndim

1

In [10]:
mtx.ndim

2

In [11]:
array.shape

(10,)

In [12]:
mtx.shape

(3, 3)

In [13]:
array.dtype

dtype('float64')

In [14]:
mtx.dtype

dtype('float64')

In [15]:
array.astype('int') # define o tipo de dado do array ou matriz.

array([ 1,  0, -1,  0, -2,  0,  0,  0, -1,  0])

In [16]:
mtx.astype('int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
array.argmax() # retorna o indice onde está o maior elemento

0

In [18]:
mtx.argmax()

2

In [20]:
array.argmin() # da mesmo forma vale para o menor valor

4

In [21]:
array.sort() # ordena o array
array

array([-2.0291442 , -1.43615399, -1.32423947, -0.22727839, -0.2243564 ,
       -0.13843418, -0.0408311 ,  0.04383233,  0.22448472,  1.74458883])

In [22]:
mtx.T # troca as linhas pelas colunas

array([[ 0.9439145 ,  0.16826415, -0.11922921],
       [ 0.48749991, -0.06389469, -0.39774131],
       [ 0.99424054, -0.28131346, -0.03310841]])

### Máscaras

In [23]:
a = np.array([1,2,3,4])

In [24]:
a[[False, True, False, True]]

array([2, 4])

In [25]:
a >= 3

array([False, False,  True,  True])

In [26]:
a[a >= 3]

array([3, 4])